### ISSUE TITLE
Please update Blynk server to blynk-cloud.com

### ISSUE THREAD

**Issue by swyngaard** [wipy/wipy#16]
See this announcement: http://community.blynk.cc/t/cloud-blynk-cc-host-is-no-longer-supported/6264

The cloud.blynk.cc server no longer works!

Also, the SSL certificate will need updating too.

**Comment by swyngaard** [comment]
#17 submitted a PR

**Comment by vshymanskyy** [comment]
It will be fixed in a different way, with the proper library update...

**Comment by swyngaard** [comment]
Great! Thanks for the news. Looking forward to the update.

**Comment by danicampora** [comment]
Solved in: https://github.com/wipy/wipy/commit/2371da3de11291141f033595681122414406491f
