### ISSUE TITLE
Hidden messages in PinOUT.xlsx

### ISSUE THREAD

**Issue by doctorjames** [wipy/wipy#4]
I've just noticed there appears to be some advertising hidden in white text in the background of the pin out diagram. Not speaking Dutch, I'm not entirely sure what it says!

**Comment by danicampora** [comment]
Hi @doctorjames can you show me where? (screenshot maybe...) I cannot see it...

**Comment by doctorjames** [comment]
Sure, see attached. (Strangely github wouldn't accept a pdf upload despite claiming it did.)

![pinout hidden text](https://cloud.githubusercontent.com/assets/317443/10353200/45330604-6d4c-11e5-9e9f-94a335f0b099.png)

**Comment by dpgeorge** [comment]
oops!

**Comment by danicampora** [comment]
Solved in https://github.com/wipy/wipy/commit/1b79563e3fb67ecc0384bc383f4ec1930fc9d5b2
