### ISSUE TITLE
Documentation: bugs in section 4.2 "assigning a static IP address"

### ISSUE THREAD

**Issue by peterhinch** [wipy/wipy#8]
The code references `net.ssid` and `net.sec` when the `net` object is undefined. The final line is a `break` statement outside of a loop.

**Comment by danicampora** [comment]
Hi thanks, yes, copy paste error in a rush, will fix it.

**Comment by danicampora** [comment]
Fixed in https://github.com/micropython/micropython/commit/9011815d862683711a6d79bb76a553d84b6e4556
